baseURL = "https://modeneis.com"
languageCode = "en-us"
title = "Modeneis Blockchain Software Development Company"
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.png"
    alt = "Modeneis Blockchain Software Development Company"

  [params.homepage_meta_tags]
    meta_description = "Modeneis was founded in the year 2017 in Amsterdam and is a dedicated lab of R&D experts for Blockchain technologies."
    meta_og_title = "Modeneis Blockchain Software Development Company"
    meta_og_type = "website"
    meta_og_url = "https://modeneis.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "odeneis was founded in the year 2017 in Amsterdam and is a dedicated lab of R&D experts for Blockchain technologies."
    meta_twitter_card = "summary"
    meta_twitter_site = "@modeneis"
    meta_twitter_creator = "@modeneis"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  [[menu.main]]
      name = "Clients"
      url = "/clients/"
        weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
